### ISSUE TITLE
Error in resulting Parser.cs

### ISSUE THREAD

**Issue by Kahdeg-15520487** [michaeldz/Coco.VSPlugin.VS2015#2]
Error in this generated code segment:
The name 'T' does not exist in the current context.
The name 'x' does not exist in the current context.

    static readonly bool[,] set = {
        {T,x,x,x, x}
    };

Error cause of mistake in method InitSet in class ParserGen:

    foreach (Symbol sym in tab.terminals) {
        if (s[sym.n]) gen.Write("T,"); else gen.Write("x,");
            ++j;
        if (j%4 == 0) gen.Write(" ");
    }
    if (i == symSet.Count-1) gen.WriteLine("x}"); else gen.WriteLine("x},");
Suggest changing the above code segment to the following:

    foreach (Symbol sym in tab.terminals) {
        if (s[sym.n]) gen.Write("_T,"); else gen.Write("_x,");
            ++j;
        if (j%4 == 0) gen.Write(" ");
    }
    if (i == symSet.Count-1) gen.WriteLine("_x}"); else gen.WriteLine("_x},");

**Comment by michaeldz** [comment]
It is not a defect of the plugin...

"_T" or "T", "_x", or "x"  or other variations of the variables are defined into **"Parser.frame"**
Different versions of the _COCO/r_ expect different naming convention of the variable.
Version that included into the plugin expect "T" and "x".

There are two fundamental aspects of the problem:
- there is no "right" version of _COCO/r_, therefore we have no a "standard"
- the plugin very close depended to the _COCO/r_. So user do not able to configure - which exactly version it should use.

Probably in future it will refactored for ability to configure version of _COCO/r_.

Now - just fix parser/scanner.frame. I have attached example.


[example.zip](https://github.com/michaeldz/Coco.VSPlugin.VS2015/files/1127281/example.zip)

**Comment by Kahdeg-15520487** [comment]
Oh thank you.

**Comment by Kahdeg-15520487** [comment]
Also if i use the scanner.frame in the attached example i get the same kind of issue.
After replaced that with the scanner.frame from the Coco/R website, it is fine now.
