### ISSUE TITLE
Upgrade for VS2019

### ISSUE THREAD

**Issue by schwarcze** [michaeldz/Coco.VSPlugin.VS2015#3]
Hello,
do you think is it possible to upgrade this project for VS 2019?
Thank You.

**Comment by michaeldz** [comment]
I hope yes, but need to investigate this. Unfortunately I little bit busy now ... So maybe in few months.

**Comment by schwarcze** [comment]
This upgrade is really simply. I made it in my local repository, but I can't push changes here.

**Comment by schwarcze** [comment]
@michaeldz Thanks for merging my changes. Please, can you publish new version to VS gallery at https://marketplace.visualstudio.com/items?itemName=MichaelDz.CocoPlugin  ?
Thank You.

**Comment by michaeldz** [comment]
Hello Erik.
Thank you for PR.
Yes sure.
But I need to test it for compatibility with previous versions of VS. I need to create virtual environments for this. So .. I will do it soon.
